### ISSUE TITLE
Installation Issues on GForth 0.7.0

### ISSUE THREAD

**Issue by RickCarlino** [GeraldWodni/f#1]
Hi Gerald,

I followed the installation directions up to step 3 when I hit the following issue:

```
SYSTEM NOT SUPPORTED, HTTP-client not implemented
```

It seems that this is because `http-slurp` is missing. It also looks like `gforth-compat.4th` defines that word, but running `gforth compat-gforth.4th f.4th` fails because `buffer:` is not defined:

```
➜  0.2.2 gforth compat-gforth.4th f.fth

in file included from *OS command line*:-1
compat-gforth.4th:8: Undefined word
buffer-max >>>buffer:<<< rbuffer  \ receiving buffer
Backtrace:
$7F6B7E744A68 throw 
$7F6B7E75ADE0 no.extensions 
$7F6B7E744D28 interpreter-notfound1 
```

Is my local version of GForth too old? I can't find a definition for `buffer:` anywhere in the source. Did I make a n00b mistake somewhere during the installation process?

**Comment by GeraldWodni** [comment]
Hi Rick,

`buffer:` is in gforth since ages, you must have a very old Gforth version installed ;)
Can you tell me the output of `gforth -v` and maybe the operating system you are using it on?

**Comment by GeraldWodni** [comment]
Hi Rick,

sorry did not see the that you included the version in the subject :confused: 
0.7.0 is very old. If you do not want to use the [bleeding edge](http://www.complang.tuwien.ac.at/forth/gforth/Snapshots/current/) consider getting the current [stable 0.7.3](http://ftp.gnu.org/gnu/gforth/gforth-0.7.3.tar.gz).

I could not pinpoint the exact version which added buffer: but I am afraid anything too old will have other troubles as well.

**Comment by RickCarlino** [comment]
@GeraldWodni Thanks! I just noticed that last night. I was running an ancient version of GForth that came from the Ubuntu PPAs.
